# Generated by Django 2.2rc1 on 2019-03-29 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20190329_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 15, 17, 46, 111737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='img1',
            field=models.ImageField(default='default.jpg', upload_to='dog_image'),
        ),
    ]
