# Generated by Django 2.1.1 on 2019-04-01 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20190329_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='additional_info',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='breed',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.IntegerField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 10, 56, 17, 139622, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
