# Generated by Django 2.1.1 on 2019-04-01 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20190401_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='breed',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 10, 59, 35, 479756, tzinfo=utc)),
        ),
    ]
