# Generated by Django 2.1.1 on 2019-04-05 05:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20190401_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='additional_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 5, 18, 40, 543453, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='img1',
            field=models.ImageField(upload_to='dog_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
