# Generated by Django 2.1.1 on 2019-04-05 05:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20190405_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 5, 23, 43, 673830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='img1',
            field=models.ImageField(default='default.jpg', upload_to='dog_image'),
        ),
    ]
