# Generated by Django 2.1.1 on 2019-04-05 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20190405_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='additional_info',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='breed',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.IntegerField(default='00'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 5, 24, 58, 110285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
