# Generated by Django 2.1.1 on 2019-04-11 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_auto_20190405_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='additional_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 7, 55, 6, 59455, tzinfo=utc)),
        ),
    ]
