# Generated by Django 2.1.1 on 2019-04-11 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_auto_20190411_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 8, 3, 32, 862362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
