# Generated by Django 2.1.1 on 2019-04-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20190416_0016'),
        ('main_page', '0012_auto_20190411_1334'),
    ]

    operations = [
    ]
